[package]
name = "recognitio"
version = "0.1.0"
authors = ["hyperum <aaronhyperum@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.10"
ontologica = {path = "../ontologica"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = {version = "0.6", features = ["stdweb"]}
ascii = "0.9.1"